####################################
# task.yml
#
# testfile for syntax highlighting
####################################

- include: ./clean_all.yml
  when: clean_all

###########################################
# create necessary directories
- name: create temp directory
  action: file path="ss{{ temp_dir }}ss" state=directory
- name: create releases directory
  file: path={{ application_dir }} state=directory
# end create necessary directories
###########################################

###########################################
# checks before deployment can start
- name: check if artifact exists
  action: "shell curl -s --head '{{ artifact_download_url }}&temp=test' | grep 'HTTP/1.[01] [23]..'"
  tags:
    - pre_checks
# end of checks before deployment can start
###########################################

###########################################
# copy nginx configuration
- name: copy nginx conf
  copy: src=nginx.conf
        dest=/etc/nginx/{{ nginx }}.conf
        owner=www-data
        group=www-data
        mode=0644
  notify: restart nginx
# end of copy nginx configuration
###########################################

###########################################
# host configuration in inventory file
[foo-bar-dev]
foo.dev.bar.com some_host_var=foo001.service.bar:7676,foo002.service.bar:7676
###########################################

- name: install bundler
  command: /home/{{ discourse.user }}/.rvm/bin/gem install creates=/home/{{ discourse.user }}/.rvm/gems/ruby-{{ ruby.global}}/bin/bundle

################################################################################
# First indented line of every play
  - name: test indented task
    command: ls
################################################################################

################################################################################
# hosts
- hosts: all!localhost
################################################################################

################################################################################
# variable defininitions
artifact_download_url: "{{ some_download_url }}/App_{{ version }}.war"
################################################################################